

# This file was *autogenerated* from the file create_challenge.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_32 = Integer(32); _sage_const_1 = Integer(1); _sage_const_31 = Integer(31); _sage_const_65537 = Integer(65537); _sage_const_16 = Integer(16)
import json

primes = [random_prime(_sage_const_2 **_sage_const_32 -_sage_const_1 , false, _sage_const_2 **_sage_const_31 ) for i in range(_sage_const_32 )]

N = prod(primes)

e = _sage_const_65537 

flag = b'dvCTF{rs4_f4ctor1z4t10n!!!}'
flag = int(flag.hex(), _sage_const_16 )

ct = pow(flag, e, N)

challenge = {"N": int(N), "e": int(e), "ct": int(ct)}

print(challenge)

with open("supersecret.json", 'w') as output:
    output.write(json.dumps(challenge))

