version: "3.9"
services:
  web:
    build: .
    ports:
      - "1337:5000"
    restart: always
  db:
    image: mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 7QL%oPx3vLuMda
      MYSQL_DATABASE: lajoute
      MYSQL_USER: guill4ume
      MYSQL_PASSWORD: v3ry_s3cure_p455w0rd
    volumes:
      - ./init/:/docker-entrypoint-initdb.d
    restart: always
